services:
  postgres:
    image: postgres:17.4-alpine3.21
    env_file:
      - ./config/app.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./config/app.env
    environment:
      - DB_SOURCE=${DB_SOURCE}
      - GIN_MODE=release
      - SERVER_ADDR=${SERVER_ADDR}
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "${DB_HOST:-postgres}:${DB_PORT}", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
    restart: unless-stopped

volumes:
  pgdata:
